// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentSendSync.Infrastructure.Context;

#nullable disable

namespace TalentSendSync.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920164250_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalentSendSync.Domain.Entities.Candidatura", b =>
                {
                    b.Property<Guid>("CandidaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("CurriculoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LinkVaga")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PretensaoSalarial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CandidaturaId");

                    b.HasIndex("CurriculoId");

                    b.ToTable("Candidaturas", (string)null);
                });

            modelBuilder.Entity("TalentSendSync.Domain.Entities.Curriculo", b =>
                {
                    b.Property<Guid>("CurriculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("CurriculoId");

                    b.ToTable("Curriculos", (string)null);
                });

            modelBuilder.Entity("TalentSendSync.Domain.Entities.HistoricoContato", b =>
                {
                    b.Property<Guid>("HistoricoContatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataContato")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TipoContato")
                        .HasColumnType("int");

                    b.HasKey("HistoricoContatoId");

                    b.HasIndex("CandidaturaId");

                    b.ToTable("HistoricosContato", (string)null);
                });

            modelBuilder.Entity("TalentSendSync.Domain.Entities.Candidatura", b =>
                {
                    b.HasOne("TalentSendSync.Domain.Entities.Curriculo", "Curriculo")
                        .WithMany("Candidaturas")
                        .HasForeignKey("CurriculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curriculo");
                });

            modelBuilder.Entity("TalentSendSync.Domain.Entities.HistoricoContato", b =>
                {
                    b.HasOne("TalentSendSync.Domain.Entities.Candidatura", "Candidatura")
                        .WithMany("HistoricosContato")
                        .HasForeignKey("CandidaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidatura");
                });

            modelBuilder.Entity("TalentSendSync.Domain.Entities.Candidatura", b =>
                {
                    b.Navigation("HistoricosContato");
                });

            modelBuilder.Entity("TalentSendSync.Domain.Entities.Curriculo", b =>
                {
                    b.Navigation("Candidaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
